# Generated by Django 2.2.10 on 2021-11-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extempore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtmfundocentry',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Whether this function is a custom one, not from the official Extempore codebase.', verbose_name='custom function?'),
        ),
    ]
